In [22]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [23]:
# pip install keras

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [25]:
tokenizer.fit_on_texts(docs)

In [26]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [27]:
tokenizer.document_count

10

In [28]:
sequence = tokenizer.texts_to_sequences(docs)

In [29]:
sequence

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [30]:
from keras.utils import pad_sequences
sequence = pad_sequences(sequence, padding='post')

In [31]:
sequence

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [46]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense , SimpleRNN, Embedding, Flatten, Input

In [59]:
model = Sequential()
model.add(Input(shape=(5,)))
model.add(Embedding(input_dim=17, output_dim=2))

model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 5, 2)           │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.compile('adam', 'accuracy')

In [62]:
pred = model.predict(sequence)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
[[[-0.01262964  0.03840912]
  [-0.03046526 -0.04937812]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]]

 [[-0.03046526 -0.04937812]
  [-0.03046526 -0.04937812]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]]

 [[ 0.01449621 -0.04702614]
  [ 0.01449621 -0.04702614]
  [-0.03483228 -0.006037  ]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]]

 [[ 0.04079062 -0.01356969]
  [-0.04839457  0.03174642]
  [ 0.04079062 -0.01356969]
  [-0.03046526 -0.04937812]
  [ 0.04079062 -0.01356969]]

 [[-0.01287963 -0.04193071]
  [ 0.03313323 -0.0274877 ]
  [-0.02011647  0.03375444]
  [-0.01744457  0.02047997]
  [ 0.01953948  0.00189509]]

 [[-0.01065429  0.0219796 ]
  [-0.01065429  0.0219796 ]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.00189509]]

 [[ 0.03245496  0.04380501]
  [ 0.03245496  0.04380501]
  [ 0.01953948  0.00189509]
  [ 0.01953948  0.0018950

In [64]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [65]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [66]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [67]:
X_train.shape

(25000, 50)

In [71]:
model = Sequential()
model.add(Input(shape=(50,)))
model.add(Embedding(10000, 2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - acc: 0.6222 - loss: 0.6177 - val_acc: 0.7896 - val_loss: 0.4481
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8265 - loss: 0.3957 - val_acc: 0.8131 - val_loss: 0.4184
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8628 - loss: 0.3320 - val_acc: 0.8018 - val_loss: 0.4388
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - acc: 0.8750 - loss: 0.3054 - val_acc: 0.7915 - val_loss: 0.4627
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - acc: 0.8822 - loss: 0.2926 - val_acc: 0.7916 - val_loss: 0.4950
